# Generated by Django 3.2 on 2023-06-21 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(2033, 'Год слишком далеко в будущем')], verbose_name='Год выпуска'),
        ),
    ]
