# Generated by Django 3.2 on 2023-06-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_genretitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
